### ISSUE TITLE
没有数据集

### ISSUE THREAD

**Issue by 11111iuaaa** [zychen-ustc/PSD-Principled-Synthetic-to-Real-Dehazing-Guided-by-Physical-Priors#1]
您好，请问您提交的是不是并没有包括你们在论文中所使用的数据集？我看到很多地方的文件路径有点奇怪。感谢！

**Comment by zychen-ustc** [comment]
您好，是的。使用的是RESIDE中的RTTS数据集。其中CLAHE部分我们直接将所有处理完成后的文件放到了一起便于训练，你可以每次load数据时都使用一次CLAHE函数来处理图片。如果需要我们的预处理图片文件，可以邮箱联系我，nnice1216@mail.ustc.edu.cn。

**Comment by zychen-ustc** [comment]
您好，数据集已经在readme中提供下载链接

**Comment by 11111iuaaa** [comment]
好的，谢谢您！
