### ISSUE TITLE
无参考指标

### ISSUE THREAD

**Issue by binwang777** [zychen-ustc/PSD-Principled-Synthetic-to-Real-Dehazing-Guided-by-Physical-Priors#11]
非常杰出的工作，是否能够提供FADE,NIQE,BRISQUE,NIMA的相关代码呢。万分感谢！

**Comment by zychen-ustc** [comment]
您好！NIQE，BRISQUE使用的都是Matlab提供的官方函数。FADE使用的是源论文主页提供的matlab代码。NIMA使用的是Github的官方实现。您可以去尝试下~ 如果找不到可以继续留言，我去找一下链接~

**Comment by hello-trouble** [comment]
感谢作者精彩的工作，论文太棒了。不过这个问题也很好啊，测试代码和数据不一致，结果就差别很大，做对比实验时感觉很不踏实。作者有空了能否帮我也发一下论文所采用的测试代码和测试数据呢？我的QQ邮箱是2095886128@qq.com.
