### ISSUE TITLE
数据集问题

### ISSUE THREAD

**Issue by Emersonzyh** [zychen-ustc/PSD-Principled-Synthetic-to-Real-Dehazing-Guided-by-Physical-Priors#13]
非常出色的工作，感谢您愿意开源代码与模型！
我对您工作中使用的数据集存在一些疑问，希望您能不吝赐教：
1. 请问您在预训练的过程中使用的OTS数据集是来源于RESIDE：v0版本（313950对图片）还是RESIDE：β版本（72135对图片）呢？是否有对数据集进行采样呢？
2. 关于finetune过程中使用的数据集，您在论文中提到使用的是URHI，但在此处使用的似乎是RTTS，或者是我产生了误解么？以及是否有进行采样呢？
希望您有时间时能够给予解答，万分感谢！

**Comment by hello-trouble** [comment]
+1，同问，也有些疑惑，怎么处理的呢？

**Comment by zychen-ustc** [comment]
您好，
1. 数据集的来源是RESIDE: v0版本。没有对数据集有采样，具体的训练步骤可以参考不同backbone原paper中给出的训练details，我完全follow了他们给出的步骤。
2. 使用的是RTTS，没有进行采样操作，使用了所有图片。在Dataloader加载图片时会有必要的裁剪与增强操作。
