### ISSUE TITLE
main.py部分丢失

### ISSUE THREAD

**Issue by gzw820** [zychen-ustc/PSD-Principled-Synthetic-to-Real-Dehazing-Guided-by-Physical-Priors#15]
非常感谢您的工作，但是在main.py中，找不到data_utils中的TrainData、ValData，您能提供一下吗？非常感谢！

**Comment by Lixia1221** [comment]
我也遇到了这个问题，请问你解决了吗

**Comment by Eazin-g** [comment]
请问你 这个问题解决了吗？

**Comment by JOoooooOOOOOoe** [comment]
能提供datautils的代码吗，我也遇到这个问题了

**Comment by zlou** [comment]
I haven't run the code myself yet but seems that the problem is the folder structure is somewhat changed. The dataset class are all in [this file](https://github.com/zychen-ustc/PSD-Principled-Synthetic-to-Real-Dehazing-Guided-by-Physical-Priors/blob/main/PSD/datasets/pretrain_datasets.py).

**Comment by zychen-ustc** [comment]
您好。非常抱歉，我在整理代码的过程中遗漏了一些路径的更新。TranData与ValData的代码包含在PSD/datasets/pretrain_datasets.py文件中。

**Comment by JOoooooOOOOOoe** [comment]
非常感谢您的回复，我有一个问题想向您请教。把图片的crop_size设置成128时候报错说某一层图片已经比卷积核小了，我可以继续修改网络吗还是得改成256



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: zychen ***@***.***&gt;
发送时间: 2022年4月2日 12:02
收件人: zychen-ustc/PSD-Principled-Synthetic-to-Real-Dehazing-Guided-by-Physical-Priors ***@***.***&gt;
抄送: JOoooooOOOOOoe ***@***.***&gt;, Comment ***@***.***&gt;
主题: 回复：[zychen-ustc/PSD-Principled-Synthetic-to-Real-Dehazing-Guided-by-Physical-Priors] main.py部分丢失 (Issue #15)





 
您好。非常抱歉，我在整理代码的过程中遗漏了一些路径的更新。TranData与ValData的代码包含在PSD/datasets/pretrain_datasets.py文件中。

**Comment by zychen-ustc** [comment]
最好是改成256。如果改变网络结构的话，你需要重新训练，而且模型performance可能会受到影响
