### ISSUE TITLE
No corresponging data was found in the finetune.py program

### ISSUE THREAD

**Issue by xiexindan** [zychen-ustc/PSD-Principled-Synthetic-to-Real-Dehazing-Guided-by-Physical-Priors#23]
finetune_datasets.py文件中，self.gt_data_dir = train_data_dir + 'retinex/'和self.gt_dir = train_data_dir + 'DCP/'数据集retinex和DCP在哪下载

**Comment by zychen-ustc** [comment]
您好，这部分代码是之前版本的代码，finetune过程并不会调用这部分代码，因而这些数据也不需要，非常抱歉给您带来麻烦了。

**Comment by xiexindan** [comment]
好的，非常感谢，您写的代码非常好，那funetune过程调用的哪部分代码？

**Comment by zychen-ustc** [comment]
参考finetune.py，在finetune_datasets.py中会调用RealTrainData_CLAHE函数

**Comment by xiexindan** [comment]
好的，非常感谢

**Comment by xiexindan** [comment]
您好，那就是只用到了RealTrainData_CLAHE函数，finetune_datasets.py中的除RealTrainData_CLAHE函数其余函数可以注释掉

**Comment by zychen-ustc** [comment]
嗯是的。

**Comment by xiexindan** [comment]
好嘞，非常感谢👍
