### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'eval'

### ISSUE THREAD

**Issue by xiexindan** [zychen-ustc/PSD-Principled-Synthetic-to-Real-Dehazing-Guided-by-Physical-Priors#24]
在运行finetune.py文件时，出现AttributeError: 'NoneType' object has no attribute 'eval'错误

**Comment by JOoooooOOOOOoe** [comment]
我也遇到类似的问题，AttributeError：“”tuple“”object has no   attribute “clamp”

**Comment by xiexindan** [comment]
> 我也遇到类似的问题，AttributeError：“”tuple“”object has no attribute “clamp”

那你最后解决了吗？

**Comment by JOoooooOOOOOoe** [comment]
> 

解决了。。小细节错误，

**Comment by zychen-ustc** [comment]
你需要检查调用eval的变量是否是一个pytorch model。

**Comment by xiexindan** [comment]
好滴好滴，谢谢您



---Original---
From: ***@***.***&gt;
Date: Thu, Apr 28, 2022 13:49 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [zychen-ustc/PSD-Principled-Synthetic-to-Real-Dehazing-Guided-by-Physical-Priors] AttributeError: 'NoneType' object has no attribute 'eval' (Issue #24)




 
你需要检查调用eval的变量是否是一个pytorch model。

**Comment by JOoooooOOOOOoe** [comment]
解决了，我是在最后generate图片时候出现的，输出的是元祖我改成张量就好了



发自我的iPhone


------------------ Original ------------------
From: xiexindan ***@***.***&gt;
Date: Tue,Apr 26,2022 10:40 AM
To: zychen-ustc/PSD-Principled-Synthetic-to-Real-Dehazing-Guided-by-Physical-Priors ***@***.***&gt;
Cc: JOoooooOOOOOoe ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: Re:[zychen-ustc/PSD-Principled-Synthetic-to-Real-Dehazing-Guided-by-Physical-Priors]AttributeError: 'NoneType' object has no attribute 'eval' (Issue #24)





  
我也遇到类似的问题，AttributeError：“”tuple“”object has no attribute “clamp”
  
那你最后解决了吗？
