### ISSUE TITLE
About the training model

### ISSUE THREAD

**Issue by LC2978** [zychen-ustc/PSD-Principled-Synthetic-to-Real-Dehazing-Guided-by-Physical-Priors#25]
I want to train your model with my own dataset, can I just execute main.py and not apply finetune.py?

**Comment by zychen-ustc** [comment]
It depends on your data. If your dataset is a large-scale synthetic dataset and you would like to train a new dehazing model from scratch, then you need to complete a two-step training process: 1) run main.py to obtain a model pre-trained on your new synthetic dataset. 2) run finetune.py to fine-tune your pre-trained model on a real-world dataset (RTTS as we used or your custom dataset). 

If your dataset includes real-world hazy data and you want to fine-tune a pre-trained model, you could directly run finetune.py on your dataset.

**Comment by LC2978** [comment]
So if I want to compare with your network, then I can only use the second method?

**Comment by zychen-ustc** [comment]
I believe it depends on the training pipeline of your method. If you use RESIDE dataset for training, then you can directly finetune our method on your dataset. If your method is trained from scratch on other dataset, then it would be better to run main.py and get a new model pre-trained on the same dataset.
The key point is that we use two dataset: synthetic dataset (OTS in RESIDE) for pre-training and real-world dataset (RTTS in RESIDE) for fine-tuning. So if your training pipeline only includes a single dataset, I would recommend you to do the comparison by finetuning directly (the second method). Note that this may lead to some advantages for our method in the comparison as we use more data in pre-training.

**Comment by LC2978** [comment]
Thank you, quick reply 0^o
