### ISSUE TITLE
finetune.py程序中的train_psnr问题

### ISSUE THREAD

**Issue by xiexindan** [zychen-ustc/PSD-Principled-Synthetic-to-Real-Dehazing-Guided-by-Physical-Priors#27]
您好，在训练完finetune.py程序时，发现train_psnr值是0?

**Comment by xiexindan** [comment]
您好，打扰您了，非常感谢您的代码，我在训练完finetune.py程序时，发现train_psnr值是0，这代表的是什么含义呢

**Comment by zychen-ustc** [comment]
可能是您的训练过程中出现了一些问题，导致模型并没有收敛。可以检查模型的输出。

**Comment by AlvinMLee** [comment]
怎么解决的

**Comment by AlvinMLee** [comment]
> 您好，在训练完finetune.py程序时，发现train_psnr值是0?

您好，请问怎么解决的
