### ISSUE TITLE
Exact NIMA implementation used?

### ISSUE THREAD

**Issue by zlou** [zychen-ustc/PSD-Principled-Synthetic-to-Real-Dehazing-Guided-by-Physical-Priors#29]
Hi, Thanks for the interesting work. 

In [This issue](https://github.com/zychen-ustc/PSD-Principled-Synthetic-to-Real-Dehazing-Guided-by-Physical-Priors/issues/11)
you mentioned you used GitHub implementation for NIMA. There are, however, three open sourced implementations. My guess is [this](https://github.com/idealo/image-quality-assessment) is the one you used. Let me know if that is the case. Beside, there are a [keras implementation](https://github.com/titu1994/neural-image-assessment) and a[ PyTorch implementation](https://github.com/yunxiaoshi/Neural-IMage-Assessment).

**Comment by zychen-ustc** [comment]
Hi! I believe the first link you mentioned is the implementation we used, but I am not 100% sure.
