### ISSUE TITLE
训练细节

### ISSUE THREAD

**Issue by RC-Qiao** [zychen-ustc/PSD-Principled-Synthetic-to-Real-Dehazing-Guided-by-Physical-Priors#31]
请问您是用的什么GPU几张训练时长是多少

**Comment by RC-Qiao** [comment]
pytorch 1.8可以么 可以在3090上跑么

**Comment by zychen-ustc** [comment]
我使用4张1080Ti约花费20小时时间进行pre-train。fine-tune过程耗时相对短很多。3090可能会带来cuda版本的问题，pytorch版本较新也有可能会出现一些小问题，不过我相信应该容易解决。

**Comment by RC-Qiao** [comment]
我也想要你使用的评估目标检测的代码，还有论文中用的epoch和您实验中的怎么不一致
