### ISSUE TITLE
测试集

### ISSUE THREAD

**Issue by RC-Qiao** [zychen-ustc/PSD-Principled-Synthetic-to-Real-Dehazing-Guided-by-Physical-Priors#32]
请问你的测试集是什么

**Comment by RC-Qiao** [comment]
我还想请问你pretrain是20轮么还是论文中的100轮 ，如果是20轮 20*12*5000（epoch*bachsize*iter） 请问20轮您收敛了么我利用20*4*15000将all__T改了跑20轮感觉没有收敛

**Comment by RC-Qiao** [comment]
还想请问finetune是4轮还是20轮 还有test中的config里面的txt是什么数据集的

**Comment by zychen-ustc** [comment]
您好！测试集使用的是RESIDE数据集中的子数据集RTTS。pre-train的epoch数主要基于backbone的选择，我的建议是依照readme中修改backbone的head之后，保持backbone原本的其它训练参数不变进行训练，包括epoch数，学习率等等。如paper内所述，finetune的epoch数是20，我在测试代码时忘记将epoch数改回了。不过基本finetune在几个epoch后就会相比backbone有一个较大的提升。
如果pre-train没有收敛的话，可以尝试对比一下backbone对应的开源代码中的训练参数。由于我们的代码包含了不同的backbone，所以当您训练某一个backbone时，可能需要重新检查并对齐参数。

**Comment by hdcxqrc** [comment]
请问pretrian是20轮还是100轮
