### ISSUE TITLE
License for this model

### ISSUE THREAD

**Issue by PINTO0309** [zychen-ustc/PSD-Principled-Synthetic-to-Real-Dehazing-Guided-by-Physical-Priors#4]
Thank you for sharing your wonderful results with us!

I have successfully converted your model to ONNX. If possible, I would like to share this model in my repository, what is the license? My model conversion scripts are released under the MIT license, but the license of the source model itself is subject to the license of the provider repository.

- My Repo
https://github.com/PINTO0309/PINTO_model_zoo

Model format that was successfully converted
1. ONNX
2. TensorFlow Lite
3. TFJS
4. TFTRT
5. CoreML
6. OpenVINO
7. Myriad Inference Blob

**Comment by PINTO0309** [comment]
1. ONNX
2. TensorFlow Lite
3. TFJS
4. TFTRT
5. CoreML
6. OpenVINO
7. Myriad Inference Blob

- Converted Models :smile: 
https://drive.google.com/file/d/1KyBlKmG1l-7Rz2K8pJfs7FWHrMPtIuV4/view?usp=sharing

**Comment by zychen-ustc** [comment]
Hi, thanks for your interest. Our models are also under the MIT license. Feel free to use them!

**Comment by PINTO0309** [comment]
Thank you!!! :smile_cat:

**Comment by PINTO0309** [comment]
Just to make sure, I'll let you know that I've committed here.
https://github.com/PINTO0309/PINTO_model_zoo/tree/main/139_PSD-Principled-Synthetic-to-Real-Dehazing-Guided-by-Physical-Priors
