### ISSUE TITLE
关于A-Net 训练存在的问题

### ISSUE THREAD

**Issue by Wsmiley** [zychen-ustc/PSD-Principled-Synthetic-to-Real-Dehazing-Guided-by-Physical-Priors#40]
作者您好，我尝试使用您提供的代码训练重新训练FFANet。
在训练的时候A-net 模块存在一些问题：
在self.layer7 = BlockUNet1(64, 64)中：
self.batch = nn.InstanceNorm2d(out_channels)
y = self.batch(y)
出现 ValueError: Expected more than 1 spatial element when training, got input size torch.Size([2, 64, 1, 1])
我看了DCPDN的代码，使用的是BatchNorm2d()。
如果将nn.InstanceNorm2d()修改为BatchNorm2d()，则不会出现此错误。
请问我该如何修改？InstanceNorm2d修改为BatchNorm2d对模型影响大吗？希望得到您的回复，感谢！

**Comment by Paphael** [comment]
我遇到了相同的问题，请问是如何解决的呢
