### ISSUE TITLE
some code errors in test.py

### ISSUE THREAD

**Issue by peylnog** [zychen-ustc/PSD-Principled-Synthetic-to-Real-Dehazing-Guided-by-Physical-Priors#5]
Thanks for you excellent work！ but , when I use test.py  ,  there are some errors .    

      Such as ,   model.cuda & net.cuda & batchnormal error.
      Can you check your test.py code?

Thanks a lot.

**Comment by yuhu-dsp** [comment]
I just met the same problem. It seems that the batchnormalization part has a great impact on the testing process!
Sincerely hope for answer!

**Comment by peylnog** [comment]
Looking forward to author's reply

**Comment by zychen-ustc** [comment]
Hi! Could you explain detailed information about your problem or provide the full error log? The testing code works well for me.

**Comment by zychen-ustc** [comment]
If you find errors like **"ValueError: Expected more than 1 value per channel when training, got input size torch.Size([1, 64, 1, 1])"** when running test.py, there are two ways to solve it:
- Resize haze_A (input of A-Net) to 512×512.
- Delete A-Net (as it is not used in testing).

I believe the error is caused by the PyTorch version. All codes work well for me in PyTorch 1.3.0.

**Comment by yuhu-dsp** [comment]
> If you find errors like **"ValueError: Expected more than 1 value per channel when training, got input size torch.Size([1, 64, 1, 1])"** when running test.py, there are two ways to solve it:
> 
> * Resize haze_A (input of A-Net) to 512×512.
> * Delete A-Net (as it is not used in testing).
> 
> I believe the error is caused by the PyTorch version. All codes work well for me in PyTorch 1.3.0.

Thank you for your kind patience! I met the very problem you mentioned above days before. But when I run the testing code today, the problem just disappears. After all the debugging process, I think the two solutions you provide are the key to this problem. Thanks a lot!

**Comment by sulakshgupta988** [comment]
When I resize haze_A, I am getting the following error 

Traceback (most recent call last):
  File "test.py", line 53, in <module>
    haze_A.resize((512,512))
  File "/usr/local/lib/python3.7/dist-packages/torch/tensor.py", line 360, in resize
    return Resize.apply(self, sizes)
  File "/usr/local/lib/python3.7/dist-packages/torch/autograd/_functions/tensor.py", line 37, in forward
    'x'.join(map(str, tensor.size())), tensor.numel()))
**RuntimeError: requested resize to (512, 512) ((512, 512) elements in total), but the given tensor has a size of 1x3x256x256 (196608 elements). autograd's resize can only change the shape of a given tensor, while preserving the number of elements.**

and I am not able to delete A_net. Can you kindly tell me how to do so?

Thank you so much

**Comment by zychen-ustc** [comment]
> When I resize haze_A, I am getting the following error
> 
> Traceback (most recent call last):
> File "test.py", line 53, in
> haze_A.resize((512,512))
> File "/usr/local/lib/python3.7/dist-packages/torch/tensor.py", line 360, in resize
> return Resize.apply(self, sizes)
> File "/usr/local/lib/python3.7/dist-packages/torch/autograd/_functions/tensor.py", line 37, in forward
> 'x'.join(map(str, tensor.size())), tensor.numel()))
> **RuntimeError: requested resize to (512, 512) ((512, 512) elements in total), but the given tensor has a size of 1x3x256x256 (196608 elements). autograd's resize can only change the shape of a given tensor, while preserving the number of elements.**
> 
> and I am not able to delete A_net. Can you kindly tell me how to do so?
> 
> Thank you so much

Hi. you could change the parameters in this [line](https://github.com/zychen-ustc/PSD-Principled-Synthetic-to-Real-Dehazing-Guided-by-Physical-Priors/blob/f200c202d08ecf8c8ef31d7821307b242e5767a0/PSD/datasets/pretrain_datasets.py#L500). Note that this only works for FFA-Net backbone.

**Comment by sulakshgupta988** [comment]
> > When I resize haze_A, I am getting the following error
> > Traceback (most recent call last):
> > File "test.py", line 53, in
> > haze_A.resize((512,512))
> > File "/usr/local/lib/python3.7/dist-packages/torch/tensor.py", line 360, in resize
> > return Resize.apply(self, sizes)
> > File "/usr/local/lib/python3.7/dist-packages/torch/autograd/_functions/tensor.py", line 37, in forward
> > 'x'.join(map(str, tensor.size())), tensor.numel()))
> > **RuntimeError: requested resize to (512, 512) ((512, 512) elements in total), but the given tensor has a size of 1x3x256x256 (196608 elements). autograd's resize can only change the shape of a given tensor, while preserving the number of elements.**
> > and I am not able to delete A_net. Can you kindly tell me how to do so?
> > Thank you so much
> 
> Hi. you could change the parameters in this [line](https://github.com/zychen-ustc/PSD-Principled-Synthetic-to-Real-Dehazing-Guided-by-Physical-Priors/blob/f200c202d08ecf8c8ef31d7821307b242e5767a0/PSD/datasets/pretrain_datasets.py#L500). Note that this only works for FFA-Net backbone.

This worked like a charm.. Thanks a lot
